### ISSUE TITLE
How to use FilePondPluginFileValidateType in reactjs?

### ISSUE THREAD

**Issue by hungdev** [pqina/filepond-plugin-file-validate-type#14]
i just want to use accept file type, so i found FilePondPluginFileValidateType, but i don't know how to  use FilePondPluginFileValidateType. Please help me.

```
import FilePondPluginFileValidateType from 'filepond-plugin-file-validate-type'

<FilePond
              ref={ref => this.pond = ref}
              allowMultiple={true}
              name="ebookFile"
              onupdatefiles={(arrFiles) => this.setState({ mailData: { ...mailData, arrFiles } })}
              // ignoredFiles={['.ds_store', 'thumbs.db', 'desktop.ini']}
              acceptedFileTypes={['image/png']}
            />
```

thank you

**Comment by Brian611** [comment]
Why was this issue closed? when it was not resolved.

**Comment by hungdev** [comment]
@Brian611  yes, i resolved it.
read docs: https://pqina.nl/filepond/docs/patterns/frameworks/react/
it config like end of part guide.
```
import { FilePond, registerPlugin } from 'react-filepond';
import FilePondPluginFileValidateType from 'filepond-plugin-file-validate-type'
import FilePondPluginFileValidateSize from 'filepond-plugin-file-validate-size';

registerPlugin(FilePondPluginFileValidateType, FilePondPluginFileValidateSize)

<FilePond
              ref={ref => this.pond = ref}
              allowMultiple={true}
              // acceptedFileTypes={acceptFileTypes}
              name="ebookFile"
              // onwarning={(err) => alert(JSON.stringify(err))}
              // onerror={(err) => alert(JSON.stringify(err))}
              onprocessfile={(error, file) => this.handlePondFile(error, file)}
              // server="http://localhost:3000/upload"
              // onaddfile={(error, file) => this.onAddFile(error, file)}
              onupdatefiles={(arrFiles) => this.setState({ mailData: { ...mailData, arrFiles } })}
              maxFileSize={'5MB'}
            />
```

i hope this help you.

**Comment by Brian611** [comment]
Thanks this solved it. registering the plugin was crucial.

**Comment by dineshtalekar777** [comment]
@hungdev - can you please share the complete working example for file size validation as this is not working in my solution I did the same thing as you shown in the above example
I have installed below packages 
npm install react-filepond filepond --save
npm i filepond-plugin-file-validate-size --save
npm i filepond-plugin-file-validate-type --save
```
<FilePond ref={ref => this.pond = ref} labelIdle="Drag & Drop a supporting document or Browse" files={this.props.campaignFormValues.files}
                            allowMultiple={true} maxFiles={3}
                            dropValidation
                            onupdatefiles={(fileItems) => {
                                this.props.fileAttachmentsChange(fileItems);
                            }}
                            maxFileSize={'10MB'}
                            >
                        </FilePond>
```

**Comment by hungdev** [comment]
maybe you forgot: 
`registerPlugin(FilePondPluginFileValidateType, FilePondPluginFileValidateSize)`

**Comment by dineshtalekar777** [comment]
@hungdev - Yes I did that also

**Comment by dineshtalekar777** [comment]
@hungdev  - Please find attached screenshots I did the same

![image](https://user-images.githubusercontent.com/13659423/106350380-11360b80-62fb-11eb-8275-fccf2d35bf75.png)

![image](https://user-images.githubusercontent.com/13659423/106350367-00859580-62fb-11eb-8eb3-f121a3d42e97.png)

**Comment by hungdev** [comment]
@dineshtalekar777 
here is an example I made it for you
https://codesandbox.io/s/relaxed-hawking-t6rhz?file=/src/App.js

**Comment by dineshtalekar777** [comment]
@hungdev  - Thanks a lot for example. I am doing the same but as I uploaded the images I am getting the compile time error for maxFileSize property

**Comment by erikkjernlie** [comment]
Same her - getting the compile error. Any updates?

**Comment by rikschennink** [comment]
@dineshtalekar777 @erikkjernlie This is a problem with the TypeScript types not loading correctly. Looking into it.

**Comment by rikschennink** [comment]
@dineshtalekar777 @erikkjernlie You can add `// @ts-ignore` above the property to temporary fix the issue.

**Comment by rikschennink** [comment]
I've done some more research and learned that TypeScript interfaces can be extended like this:

```ts
interface MyInterface {
  label: string;
}
```

Now add `additionalLabel` to our `MyInterface` interface.
```ts
interface MyInterface {
  additionalLabel: string;
}
```

Which should help with making the FilePond plugin interfaces a bit easier to set up. So will probably get to fixing this next week.

**Comment by rikschennink** [comment]
Just updated type decorations for every plugin. should fix the issue.
