### ISSUE TITLE
Is there any way to replace acceptedFileTypes with rejectedFileTypes?

### ISSUE THREAD

**Issue by yaharga** [pqina/filepond-plugin-file-validate-type#17]
Instead of listing types of accepted files, I want to list out a list to reject files if the types are those. Is there any easy way of doing this?

**Comment by rikschennink** [comment]
Hi, no there is not, the `acceptedFileTypes` property partly reflects the functionality of the `accept` attribute. You might be able to use the `fileValidateTypeDetectType` hook to filter out invalid types.

**Comment by yaharga** [comment]
Thanks @rikschennink . I ended up using this solution. It's not the best, but it works.

    fileValidateTypeDetectType={(source, type) => new Promise((resolve, reject) => {
      let rejectedExtensions = ['ade', 'adp', 'apk', 'bat', 'chm', 'cmd', 'com', 'cpl', 'dll', 'dmg', 'exe', 'hta', 'ins', 'isp', 'jar', 'js', 'jse', 'lib', 'lnk', 'mde', 'msc', 'msi', 'msp', 'mst', 'nsh', 'pif', 'scr', 'sct', 'shb', 'sys', 'vb', 'vbe', 'vbs', 'vxd', 'wsc', 'wsf', 'wsh', 'cab']; // List of rejected file types from Gmail
      // If the file extension is not in our rejected list.
      if (!rejectedExtensions.some(ext => source.name.endsWith("." + ext))) {
        resolve('notRejected');
      }
      // Otherwise it is rejected.
      resolve(type);
    })}
