### ISSUE TITLE
acceptedFileTypes not working

### ISSUE THREAD

**Issue by ronaldohoch** [pqina/filepond-plugin-file-validate-type#19]
Hello! I'm using Angular 6 and today i installed the FileValidationType plugin but, the plugin only acepts 

acceptedFileTypes: ['image/png'], when i change to acceptedFileTypes: ['image/jpg'], the plugin don't work properly, when i put "image/png" the plugin even blocks another file type.

![image](https://user-images.githubusercontent.com/2287371/62164881-8d5d2680-b2f3-11e9-9e7a-d531127e0330.png)
![image](https://user-images.githubusercontent.com/2287371/62164910-9fd76000-b2f3-11e9-8d06-f1b20f2c3947.png)
![image](https://user-images.githubusercontent.com/2287371/62165076-ff357000-b2f3-11e9-8f8b-b04b92122a8d.png)

**Comment by rikschennink** [comment]
The type should be “image/jpeg” not “image/jpg”

**Comment by ronaldohoch** [comment]
Worked! Thank You!
