### ISSUE TITLE
Issue when try validate CSV

### ISSUE THREAD

**Issue by j0ssGZ** [pqina/filepond-plugin-file-validate-type#2]
Hi guys! I recently started using vue filepond and it's great for me! The problem is that when I apply this plugin and try to validate a csv type, there is NO WAY 😅.

Always return next msg:
![image](https://user-images.githubusercontent.com/6393898/38803449-9484f970-416f-11e8-9e03-28229bdc6a1b.png)

If delete `acceptedFileTypes` works fine, and too with other types like `image/png, image/jpg`, etc, but never with CSV. Any suggest?

Thanks for the great job, greetings!

**Comment by j0ssGZ** [comment]
After testing it definitely I think the problem is Windows, since in its file browser does not allow filtering only by extension csv (marks all files). If I delete application / vnd.ms-excel and leave the other two, despite letting me choose any file, it only works with the csv, so I think that's fine.

For my part it can be closed, the end of the plugin works perfectly.

Have a good day =)

**Comment by Bilguunkhan** [comment]
Hello, I love file-pond, great work guys! However, I have been trying to upload a csv file and I have tried the above solutions, but the issue persists. Im using chrome on windows 7.
![giva1](https://user-images.githubusercontent.com/11615608/45069936-8c327200-b101-11e8-9819-957a0caebeab.png)
![giva2](https://user-images.githubusercontent.com/11615608/45069938-8ccb0880-b101-11e8-92ee-02d067e3b765.png)

**Comment by rikschennink** [comment]
@Bilguunkhan Please check the mime type of the file with this webpage and add the resulting mime type to the list:
https://codepen.io/rikschennink/details/NzRvbj/

At the moment FilePond does not support extensions.

Please only submit GitHub issues, don't send emails as well. Double posting does not get you help quicker.

**Comment by caribouflex** [comment]
Hey guys ! 

This has been close, but is there some news about it ? Because the issue is still happening on windows. The mime type of the file is empty.

Thanks.

**Comment by rikschennink** [comment]
@caribouflex you can use the `fileValidateTypeDetectType` property to manually return a mime type based on the extension: https://pqina.nl/filepond/docs/patterns/plugins/file-validate-type/#custom-type-detection

**Comment by caribouflex** [comment]
Oh perfect ! Can't believe I missed that ! Thanks @rikschennink

**Comment by nikhilknoldus** [comment]
Hi @j0ssGZ For your comment (https://github.com/pqina/filepond-plugin-file-validate-type/issues/2#issuecomment-381877522) I am not sure how it worked for you, because when I used these two "text/csv, application/csv" I was able to see All files but when I select CSV it doesn't work at all. And when I have `application/vnd.ms-excel` it works for me.
Any idea please ?

**Comment by cRAN-cg** [comment]
My solution was specific to the Windows OS

```
<file-pond
    name="fileUploader"
    ref="pond"
    v-bind:label-idle="getUploaderIdleLabel"
    v-bind:accepted-file-types="supportedMIMETypes"
    v-bind:files="files"
    v-bind:fileValidateTypeDetectType="getCustomMIMEType"
  />
```

```
...
getCustomMIMEType: function getCustomMIMEType(source, type) {
      if (window.navigator.platform.indexOf('Win') > -1) {
        if (type === 'application/vnd.ms-excel') type = 'text/csv'
      }
      return Promise.resolve(type)
    }
...
```

**Comment by avillarubia** [comment]
@rikschennink hi good day, I will just let you know still it won't support csv

**Comment by avillarubia** [comment]
@rikschennink hi, I observed that it won't accept all of this at once

```js
[
    "application/x-freearc",
    "application/vnd.amazon.ebook",
    "application/octet-stream",
    "application/x-bzip",
    "application/x-bzip2",
    "application/x-csh",
    "text/css",
    "text/csv",
    "application/msword",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "application/vnd.ms-fontobject",
    "application/epub+zip",
    "application/gzip",
    "text/html",
    "text/calendar",
    "application/java-archive",
    "text/javascript",
    "application/json",
    "application/ld+json",
    "application/vnd.apple.installer+xml",
    "application/vnd.oasis.opendocument.presentation",
    "application/vnd.oasis.opendocument.spreadsheet",
    "application/vnd.oasis.opendocument.text",
    "application/ogg",
    "application/pdf",
    "application/x-httpd-php",
    "application/vnd.ms-powerpoint",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "application/vnd.rar",
    "application/rtf",
    "application/x-sh",
    "application/x-shockwave-flash",
    "application/x-tar",
    "text/plain",
    "application/vnd.visio",
    "application/xhtml+xml",
    "application/vnd.ms-excel",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "application/xml",
    "application/vnd.mozilla.xul+xml",
    "application/zip",
    "application/x-7z-compressed"
]
```

**Comment by jshamg** [comment]
please reopen. widows CSV validation failure has something todo with windows Home edition and windows Pro edition.

**Comment by Dhruvi289** [comment]
Please reopen the issue. I have the same issue for csv file validation

**Comment by marcomessa** [comment]
> My solution was specific to the Windows OS
> 
> ```
> <file-pond
>     name="fileUploader"
>     ref="pond"
>     v-bind:label-idle="getUploaderIdleLabel"
>     v-bind:accepted-file-types="supportedMIMETypes"
>     v-bind:files="files"
>     v-bind:fileValidateTypeDetectType="getCustomMIMEType"
>   />
> ```
> 
> ```
> ...
> getCustomMIMEType: function getCustomMIMEType(source, type) {
>       if (window.navigator.platform.indexOf('Win') > -1) {
>         if (type === 'application/vnd.ms-excel') type = 'text/csv'
>       }
>       return Promise.resolve(type)
>     }
> ...
> ```

This was exactly my issue! I think it happens in Windows Systems with excel installed, with the option to automatically open any csv file with it. Thank you, you saved my day!

**Comment by itsameandrea** [comment]
Hey team! This is still not working for me and I'm not on Windows.

Even when forcing the type like so

```
import { Controller } from '@hotwired/stimulus'
import * as FilePond from 'filepond'
import FilePondPluginFileValidateType from 'filepond-plugin-file-validate-type'

export default class extends Controller {
  static targets = ['input']

  connect() {
    FilePond.registerPlugin(FilePondPluginFileValidateType)
    this.filePond = FilePond.create(this.inputTarget, {
      storeAsFile: true,
      acceptedFileTypes: ['text/csv'],
      fileValidateTypeDetectType: (source, type) => Promise.resolve('text/csv')
    })
  }
}
```

I get this error

![image](https://github.com/user-attachments/assets/e787ae83-1d61-4597-b6b5-ae7f737db91d)

I submitted my file through [this](https://codepen.io/rikschennink/details/NzRvbj/) and the file does have the correct mimetype.
