### ISSUE TITLE
PEM file verify failed by use filepond-plugin-file-validate-type

### ISSUE THREAD

**Issue by MarkDcc** [pqina/filepond-plugin-file-validate-type#23]
I want to use filepond-plugin-file-validate-type plugin to verify file type. I want file extension with pem(as you know brower engine may get empty MIME type for file) or file MIME type with application/x-x509-ca-cert are through verifying. So I implement fileValidateTypeDetectType(For pem file I got empty MIME type). According to the doc I only need add application/x-x509-ca-cert to acceptedFileTypes and implement fileValidateTypeDetectType like below in FilePond.

```
acceptedFileTypes = {['application/x-x509-ca-cert']}
fileValidateTypeDetectType= {(source, type) => new Promise((resolve, reject) => {
if(!(null === source.name) && source.name.includes('pem')){

                                  resolve('application/x-pem-file');
                                  
                                }else  {
                                
                                  reject(type);
                                }
                                // do custom type detection here and return with promise
                               
                            })}
```
But I got failed. I need to change my code like below,

```
acceptedFileTypes = {['application/x-x509-ca-cert','application/x-pem-file']}
fileValidateTypeDetectType= {(source, type) => new Promise((resolve, reject) => {

                                var typeMode=new Array("application/x-x509-ca-cert","application/x-pem-file")
                                if(!(null === source.name) && source.name.includes('pem')){

                                  resolve('application/x-pem-file');
                                  
                                }else if(!typeMode.includes(type)) {

                                  reject(type);
                                }
                                // do custom type detection here and return with promise
                               
                            })}
```
So my questions are:

whether fileValidateTypeDetectType only check MIME type not in acceptedFileTypes ?
why I still need to add application/x-pem-file in acceptedFileTypes ?
I want to know verify sequence about acceptedFileTypes and fileValidateTypeDetectType? because if I use the first code segment to verify a file with application/x-x509-ca-cert MIME type will be failed unless use the second code segment. That test should be pass. Is first to check MIME type whether in acceptedFileTypes and then check fileValidateTypeDetectType whether return a MIME type? If not in the above checklist should be failed.

**Comment by MarkDcc** [comment]
"filepond": "4.3.3",
    "filepond-plugin-file-validate-size": "2.1.3",
    "filepond-plugin-file-validate-type": "1.2.4",
    "filepond-polyfill": "1.0.4",

**Comment by MarkDcc** [comment]
Sorry for repeat open case, I modified code style.

**Comment by rikschennink** [comment]
@MarkDcc I'm sorry to ask but can you please format the code snippets, it's very difficult to read.

**Comment by MarkDcc** [comment]
snippet01
`	acceptedFileTypes = {['application/x-x509-ca-cert']}
	fileValidateTypeDetectType= {(source, type) => new Promise((resolve, reject) => {
		if(!(null === source.name) && source.name.includes('pem')){

			resolve('application/x-pem-file');
                                  
		}else  {
                                
			reject(type);
                }
                                // do custom type detection here and return with promise                   
            })}`
snippet01
`	acceptedFileTypes = {['application/x-x509-ca-cert','application/x-pem-file']}
	fileValidateTypeDetectType= {(source, type) => new Promise((resolve, reject) => {

        var typeMode=new Array("application/x-x509-ca-cert","application/x-pem-file")
		
        if(!(null === source.name) && source.name.includes('pem')){

			resolve('application/x-pem-file');
			
        }else if(!typeMode.includes(type)) {

            reject(type);
                                
		}
        // do custom type detection here and return with promise
                               
			})}`

**Comment by rikschennink** [comment]
If the `acceptedFileTypes` array is empty all files are allowed. That's why it needs a value to trigger type checking.

**Comment by rikschennink** [comment]
closed because inactive
