### ISSUE TITLE
Message to indicate the allowed file types should not show `or` if only one file.

### ISSUE THREAD

**Issue by caribouflex** [pqina/filepond-plugin-file-validate-type#25]
**Error:** 
When you allow only one file, for example `text/csv`, and you select a different file type, the error message will be : `Expects or text/csv`. 

**Expected:**
We would expect to see the following error message :  `Expect text/csv`. 

**Note:**
However, this works fine if you allow more than 1 file type.

**Comment by rikschennink** [comment]
You can update the `fileValidateTypeLabelExpectedTypes` label to match a singular value.

`'Expects {allButLastType} or {lastType}'` to `'Expects {lastType}'`

**Comment by caribouflex** [comment]
This is exactly what I ended to do, I saw that while I was testing the plugin, so I just created an issue. 
Feel free to close this issue, if you don't plan to change anything and as there is a workaround ! 
Thank you very much !

**Comment by rikschennink** [comment]
@caribouflex will close for now, I do agree that it would be nice to handle this internally but I think it's fine for now.
