### ISSUE TITLE
acceptedFileTypes not working for .edi file

### ISSUE THREAD

**Issue by patelvarun** [pqina/filepond-plugin-file-validate-type#30]
I am trying to validating .edi file.
I checked to validate the type from the below link. But it's also not providing valid mime-type for .edi file.
https://www.npmjs.com/package/filepond-plugin-file-validate-type
https://codepen.io/rikschennink/pen/NzRvbj

I tried with some valid mime-types for .edi files but no one is working for me.

```js
acceptedFileTypes={[
                                      'application/vnd.ibm.electronic-media',
                                      'application/EDI-consent',
                                      'application/EDIFACT',
                                      'application/EDI-X12',
                                      'application/edi-consent',
                                      'application/application/edi-x12',
                                      'application/edi-x12',
                                      'application/edifact',
]}
```

**Comment by rikschennink** [comment]
@patelvarun I could add a property that lets you stop FilePond from setting the `accept` attribute in which case the user can select all files and full validation takes place in FilePond?

**Comment by patelvarun** [comment]
> @patelvarun I could add a property that lets you stop FilePond from setting the `accept` attribute in which case the user can select all files and full validation takes place in FilePond?

Thanks. sorry for the late reply. I handled it some other way. we can close this.
