### ISSUE TITLE
Cannot access file validate type plugin properties as props for FilePond in React

### ISSUE THREAD

**Issue by ravivarma-dot** [pqina/filepond-plugin-file-validate-type#31]
I'm using FilePond and `FilePondPluginFileValidateType` in React-Typscript application. I have registered the plugin using `registerPlugin(FilePondPluginFileValidateType);` and added mimetypes in `acceptedFileTypes` prop for FilePond component. It's all good till here. The documentation says FilePondPluginFileValidateType package has a property `labelFileTypeNotAllowed `to display custom error message when user uploads a invalid file type. But FilePond doesn't have a prop for `labelFileTypeNotAllowed`. 

Below is my code and usage:

```
import React from "react";
import { FilePond, registerPlugin } from "react-filepond";
import "filepond/dist/filepond.min.css";
import FilePondPluginFileValidateType from "filepond-plugin-file-validate-type";

registerPlugin(FilePondPluginFileValidateType);

const Attachment = () => {
  return (
    <>
      <h5>Upload Files</h5>
      <FilePond
        allowMultiple={true}
        maxFiles={4}
        acceptedFileTypes={[
          "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
          'application/msword',
          'application/vnd.ms-excel',
          'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
          'application/pdf'
        ]}
        //labelFileTypeNotAllowed='File type not allowed'   <<<<<<Error here 
        allowRevert={false}
      />
    </>
  );
};

export default Attachment;

```

See below image for error and (some css issue too when mime types are long)

![image](https://user-images.githubusercontent.com/64154058/83456048-f68a5a80-a42c-11ea-84a9-14bc62c547e7.png)

**Comment by rikschennink** [comment]
`labelFileTypeNotAllowed` is dynamically added to the React component when the plugin is registered, not sure how to do that with TypeScript, can you add a temporary `// @ts-ignore` statement?

**Comment by rikschennink** [comment]
closed because inactive

**Comment by rikschennink** [comment]
Just updated all plugin type declarations, should be fixed now.
