### ISSUE TITLE
Drag and drop folder mode is abnormal

### ISSUE THREAD

**Issue by cnsdwu** [pqina/filepond-plugin-file-validate-type#32]
fileValidateTypeDetectType: (source, type) =>
    new Promise((resolve, reject) => {
      const fileName = source.name;
      const lastIndexOf = fileName.lastIndexOf(".");
      if (lastIndexOf != -1) {
        const fileExt = fileName.slice(lastIndexOf + 1);
        const acceptStr = "rar,zip,pdf,rm,avi,xls,txt,doc,docx,wps,rtf,gz,jpg,bmp,gif,png,jpeg,tif,wav,mp3,wma,aac,flac,mpg,mov,swf,wav,chm,pptx,ppt,ico,psd,tiff,webp,svg,rmvb,xlsx,flv,mvb,mp4";
        if (acceptStr.split(",").indexOf(fileExt) != -1) {
          resolve(type);
        }
      }
      reject(type);
    }),
  acceptedFileTypes: ["image/*", "audio/*", "video/*", "application/*", "text/*", "application/x-rar-compressed"],

Docx file under folder display type invalid

**Comment by rikschennink** [comment]
Please format code snippet and describe more clearly what the problem is.

**Comment by rikschennink** [comment]
closed because inactive
