### ISSUE TITLE
CSV file type issue

### ISSUE THREAD

**Issue by nikhilknoldus** [pqina/filepond-plugin-file-validate-type#33]
When I have `acceptedFileTypes="application/vnd.ms-excel, text/csv` I see option like below, 
https://user-images.githubusercontent.com/6393898/38854435-c21ea6d6-4220-11e8-9195-0a4e24f3f698.png

I just wanted to see, `All Files` and for this when I remove `application/vnd.ms-excel,` it works but when I select `csv` file, it doesn't work, it rejects by saying file type not supported, it should be `csv`.

Please resolve this issue.

**Comment by rikschennink** [comment]
https://github.com/pqina/filepond-plugin-file-validate-type/issues?q=is%3Aissue+is%3Aclosed+csv
