### ISSUE TITLE
Unable to use FilePondPluginFileValidateType plugin in spfx react

### ISSUE THREAD

**Issue by thepower50** [pqina/filepond-plugin-file-validate-type#37]
I have installed filepond@4.20.1, react-filepond@7.1.0 and filepond-plugin-file-validate-type@1.2.5.

My code includes the code

`import { FilePond, registerPlugin } from 'react-filepond';
import 'filepond/dist/filepond.min.css';
import FilePondPluginImageExifOrientation from 'filepond-plugin-image-exif-orientation';
import FilePondPluginImagePreview from 'filepond-plugin-image-preview';
import FilePondPluginFileValidateType from 'filepond-plugin-file-validate-type';`

registerPlugin(FilePondPluginFileValidateType)`

However it is not picking up fileValidateTypeDetectType when used in following code

` <FilePond files={this.state.files}
                       acceptedFileTypes={['image/png', 'application/vnd.ms-outlook']}                       
                       fileValidateTypeDetectType = {(source, type) => new Promise((resolve, reject) => {        
                        // read source data and determine type of file here, you can use extension or actually read the file data
                      })} 
                       allowMultiple={false}                                         
                       onupdatefiles={fileItems => {
                          this.setState({
                              files: fileItems.map(fileItem => fileItem.file)
                          });
                        }}            
              />`

When i run gulp serve --nobrowser I get the following error
Error - [tsc] src/webparts/spfxReactDropzone/components/SpfxReactDropzone.tsx(144,15): error TS2322: Type '{ files: any[]; acceptedFileTypes: string[]; fileValidateTypeDetectType: (source: any, type: any) => Promise<{}>; allowMultiple: false; onupdatefiles: (fileItems: FilePondFile[]) => void; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<FilePond> & Readonly<FilePondProps> & Readonly<{ children?: ReactNode; }>'.

Please can anyone advise me on what the issue is.  i am trying to drag and drop file directly from outlook so I need to include the detection of the mime type for the msg extension.

**Comment by rikschennink** [comment]
Can you please format the code snippets? Add a console log to the `fileValidateTypeDetectType` method to see if the code runs.

**Comment by rikschennink** [comment]
This is probably a TypeScript issue (tsc) should be fixed with latest release. will close because inactive.
