### ISSUE TITLE
CSV in Windows Home not detecting type

### ISSUE THREAD

**Issue by jshamg** [pqina/filepond-plugin-file-validate-type#39]
https://github.com/pqina/filepond-plugin-file-validate-type/issues/2

I have the same issue the guys in this thread had. 

csv files can't detect a mime type in Windows 10 Home. The exact same windows build in Windows 10 Pro edition is able to detect it. 

The dirty Workaround is to match by the File name:
```
getCustomMIMETypeForWindows(source: File, type: string) {
    if (window.navigator.platform.indexOf('Win') > -1) {
      if (source.name.endsWith('.csv') || source.name.endsWith('.CSV')) type = 'text/csv'
    }
    return Promise.resolve(type)
  }
```

Please Fix this issue asap, were currently using filepond in a production environment.
Cheers!

**Comment by rikschennink** [comment]
Please stick to the other thread.

> Please Fix this issue asap, we're currently using filepond in a production environment.

You're using a free product I ask you kindly to not put pressure on maintainers. Instead, consider donating or sponsoring.
