### ISSUE TITLE
Excel files (.xls) allowed to be selected but then reported as invalid type

### ISSUE THREAD

**Issue by rayax86** [pqina/filepond-plugin-file-validate-type#4]
I am trying to upload a `.xls` file which has been given permission by specifying (in Vue):

`accepted-file-types="application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"`

While `.xlsx` files are uploaded smoothly, when trying to upload a `.xls` file, the dialog will allow me to select the `.xls` file but will then report the file is not of valid type:

![Allowed to select](https://i.imgur.com/LpRxNTk.png)
![Not valid type](https://i.imgur.com/3LUNALw.png)

Checking the MIME type on terminal (on a mac):
```
file --mime "Workbook1.xls"
Workbook1.xls: application/vnd.ms-excel; charset=binary
```

**Comment by rikschennink** [comment]
The browser has an internal hash table linking up the extension to a mime type. It's probably different from the terminal one ( so MacOS might be handling it differently than Safari ).

Here's an overview of possible `.xls` mime types:
https://stackoverflow.com/questions/974079/setting-mime-type-for-excel-document

**Comment by rayax86** [comment]
@rikschennink Thank you very much, it does turn out to be browser specific (Chrome 66 on macOS 10.12.6), however, I cannot fix it by adding all these potential MIME types to the allowed list.

**Comment by rikschennink** [comment]
@rayax86 The mime types don't fix it, or are you not willing to add them?

**Comment by rayax86** [comment]
@rikschennink Ah, sorry my comment was ambiguous. I added all those mime types to the allowed list listed however filepond still doesn't allow me to upload a `.xls` file.

**Comment by rikschennink** [comment]
@rayax86 Alright, I'll see if I can reproduce the issue.

**Comment by rayax86** [comment]
@rikschennink I think it can be very browser specific because the file you gave me also failed the test.

**Comment by rikschennink** [comment]
@rayax86 It's Chrome 66.0.3359.181 on MacOS High Sierra ( 10.13.4 )

Can you add it to this file input element and see what mime type it shows:
https://codepen.io/rikschennink/pen/NzRvbj

**Comment by rayax86** [comment]
@rikschennink Ah-ha, the `p` tag is empty after `.xls` files are uploaded. Both mine and yours.

My Chrome is version 66.0.3359.181 (Official Build) (64-bit) so our only difference is the version of the macOS.

**Comment by rikschennink** [comment]
@rayax86 It seems this is a bug that only occurs on MacOS 10.12 combined with Chrome, and then only for Excel documents ( it functions correctly on Safari and other mime types do work ). Just asked some other devs to test and they can reproduce it.

Found this thread on a different support forum but it's most likely the same problem:
https://community.box.com/t5/Archive-Forum/Can-t-edit-excel-docs-MacOS-Sierra/td-p/23585

**Comment by rikschennink** [comment]
I think they only way around this is to allow matching extensions as well.

**Comment by rayax86** [comment]
I tried that but it doesn't seem to be working. The way I did so is to set
the allowed list to `'.xls, xlsx'`.

**Comment by rikschennink** [comment]
It's not implemented yet.

**Comment by rikschennink** [comment]
I think this is solved with the new `fileValidateTypeDetectType` property with which you can manually determine the type (either using the extension or reading the actual file data).

**Comment by flyer1** [comment]
I'll just add my 2 cents here b/c I was running into the same issue and this is how I fixed it.
I also used the `fileValidateTypeDetectType` property and pointed it to the function below.
Using Angular 8 and Typescript:
```
  /** Parse out the type of file selected by the user. Will be used to validate it against the acceptedFileTypes */
    getFileType(file: File, type: string): Promise<string> {
        // Note, the type property passed to this function is always blank (at least on Chrome). Therefore, pull it off of the name of the file.
        let fileType = '';
        const index = file.name.lastIndexOf('.');
        if (index > 0) {
            fileType = file.name.substr(index);
        }
        return Promise.resolve(fileType);
    }
```

**Comment by Sugeeta32** [comment]
> @rayax86 It seems this is a bug that only occurs on MacOS 10.12 combined with Chrome, and then only for Excel documents ( it functions correctly on Safari and other mime types do work ). Just asked some other devs to test and they can reproduce it.
> 
> Found this related Chromium discussion:
> https://groups.google.com/a/chromium.org/forum/#!topic/chromium-discuss/45zsF7K7NNY
> 
> I think it's this bug:
> https://bugs.chromium.org/p/chromium/issues/detail?id=155455&q=xls&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

this still seems to be a problem with mac 10x + Chrome.
