### ISSUE TITLE
It does.

### ISSUE THREAD

**Issue by Hariswebdesign** [pqina/filepond-plugin-file-validate-type#41]
It does.

_Originally posted by @rikschennink in https://github.com/pqina/filepond-plugin-file-validate-type/issues/40#issuecomment-799238874_

### Here is my code. Can't support the SVG file. Please advise. or share a **code pen** demo supporting upload SVG file.
**SVG file can't support while using (FilePondPluginFileValidateType) . I want to validate the uploaded item.**

FilePond.create(
	document.querySelector('.filepond-un-logo'),
	{
		labelIdle: `Drag & Drop Image or <span class="filepond--label-action">Browse</span>`,
		imageCropAspectRatio: '1:1',
		// maxTotalFileSize: '1MB',
		labelMaxFileSizeExceeded: 'File is too big',
		labelMaxFileSize: 'Maximum file size support {filesize}',
		labelMaxTotalFileSizeExceeded: 'Maximum total size exceeded',
		labelMaxTotalFileSize: 'Maximum total file size is {filesize}',
		files: [{
			source: "images/logo.svg",
			options: {
				type: 'localhost',
			}
		}]
	}
);

**Comment by rikschennink** [comment]
“It does” is not a valid issue title, the description also doesn’t really make sense. So closed.

**Comment by Hariswebdesign** [comment]
> “It does” is not a valid issue title, the description also doesn’t really make sense. So closed.

Ok Thanks
