### ISSUE TITLE
Can we validate if the file type is not malicious?

### ISSUE THREAD

**Issue by jazzbotdev** [pqina/filepond-plugin-file-validate-type#42]
For example, if I have only allowed .pdf to be uploaded. Currently if I create a .exe file, rename it to .pdf and try to upload it goes through. Is there a way to block such malicious files or validate if the file is truly a pdf or jpg etc?

**Comment by rikschennink** [comment]
You have to check on the server. You could add JavaScript that actually inspects the file contents, BUT as it's JavaScript you can disable it from the client so it's not _real_ security. Always check your files on the server.
