### ISSUE TITLE
Preconfigurated filetype lists

### ISSUE THREAD

**Issue by martinschilliger** [pqina/filepond-plugin-file-validate-type#5]
On https://github.com/pqina/filepond-plugin-file-validate-type/issues/4#issuecomment-395330700 @rikschennink wrote, that he is planing to support file-extensions as alternative to MIME-types.
Maybe it help to have predefined lists with MIME-types?

Like:
```
acceptedFileTypes: [
  "image/*",
  "application/pdf",
  "text/*",
  "application/msword",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "application/vnd.ms-excel",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "application/vnd.ms-powerpoint ",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  "application/vnd.oasis.opendocument.text",
  "application/vnd.oasis.opendocument.spreadsheet",
  "application/vnd.oasis.opendocument.graphics",
  "application/vnd.oasis.opendocument.chart",
  "application/vnd.oasis.opendocument.formula",
  "application/vnd.oasis.opendocument.image",
  "application/x-iwork-pages-sffpages",
  "application/x-iwork-numbers-sffnumbers",
  "application/x-iwork-keynote-sffkey",
  "audio/*",
  "video/*",
  "message/*",
  "application/zip"
]
```

What do you think?

**Comment by rikschennink** [comment]
Would be useful I think as long as they're sorted by file group/type, for instance a list for excel, images supported on web, documents, etc.

**Comment by rikschennink** [comment]
I think this is solved with the new `fileValidateTypeDetectType` property with which you can manually determine the type (so basically you could map an extension to a mime type).
https://pqina.nl/filepond/docs/patterns/plugins/file-validate-type/

**Comment by rikschennink** [comment]
I think this is solved with the new `fileValidateTypeDetectType` property with which you can manually determine the type (so basically you could map an extension to a mime type).
https://pqina.nl/filepond/docs/patterns/plugins/file-validate-type/
