### ISSUE TITLE
[Bug] Error uploading files from folder when Drag n Drop

### ISSUE THREAD

**Issue by cavasinf** [pqina/filepond-plugin-file-validate-type#50]
Weird case here, and hard to explain..

When this plugin is enabled, and using custom type detection (`fileValidateTypeDetectType` option).
Some function parameters are not filled completely like `type` or `source.type` in certain cases.

For me it's when I upload a folder with `.docx` files inside.
With that folder, `type` and `source.type` are empty strings.

But when I upload a folder with `.png`, there's no problem.

I've made a video that shows what is going on/wrong.
(Don't play the video from Google Drive, download it)
https://drive.google.com/file/d/1-1G2v6AomlVhsYSffLwibOV11CtJ8EB5/view?usp=sharing

Timestamp:
0:00 - Show `console.log()` of source and type in `fileValidateTypeDetectType` function
0:09 - Upload a folder with .png ✔️ 
0:12 - Show working folder content
0:14 - Show non-working folder content (only .docx)
0:18 - Upload folder with .docx ❌ 
0:25 - console.log from code print empty strings for .docx folder ❌ 
0:32 - Upload single .docx file ✔️ 
0:33 - console.log is not empty when one file only ✔️ 
0:38 - test with another docx file ✔️ 
0:42 - reupload non-working folder ❌ 
0:44 - console.log still empty ❌ 

Here is my fileType param (`acceptedFileTypes` option) : 
```php
[
  0 => "video/mp4"
  1 => "video/mp4v-es"
  2 => "video/x-m4v"
  3 => "video/quicktime"
  4 => "video/x-flv"
  5 => "application/x-flash-video"
  6 => "flv-application/octet-stream"
  7 => "video/flv"
  8 => "video/avi"
  9 => "video/divx"
  10 => "video/msvideo"
  11 => "video/vnd.divx"
  12 => "video/x-avi"
  13 => "video/x-msvideo"
  14 => "image/jpeg"
  15 => "image/pjpeg"
  16 => "image/jpeg"
  17 => "image/pjpeg"
  18 => "image/png"
  19 => "image/tiff"
  20 => "image/tiff"
  21 => "text/plain"
  22 => "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
  23 => "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
  24 => "application/pdf"
  25 => "application/acrobat"
  26 => "application/nappdf"
  27 => "application/x-pdf"
  28 => "image/pdf"
]
```

### Device
Device: Computer
OS: Windows 10
Browser: Firefox 99.0.1 (64 bits)

### Package
filepond-plugin-file-validate-size@^2.2.6
filepond-plugin-file-validate-type@^1.2.6
filepond-plugin-image-preview@^4.6.10
filepond@^4.30.3

**Comment by rikschennink** [comment]
File types are detected by the file system, docx type detection even differs when you have office installed vs when not.

Will close because FilePond just passes the files through that function, it doesn't do anything with the types.

**Comment by cavasinf** [comment]
Ok, so what is the difference between :
- uploading a single file .docx (which is working) ✔️ 
- upload a folder with two .docx ❌

**Comment by rikschennink** [comment]
I don't know, probably that it tries to guess the mime type of the file
https://github.com/pqina/filepond/blob/master/src/js/app/utils/requestDataTransferItems.js#L163
