### ISSUE TITLE
fileValidateTypeDetectType not working as expected

### ISSUE THREAD

**Issue by lnfel** [pqina/filepond-plugin-file-validate-type#51]
> "filepond": "^4.30.4"
    "filepond-plugin-file-validate-type": "^1.2.8"
    "vue-filepond": "^6.0.3"

Hi, I just encountered a weird scenario when using type validation plugin. Everything works fine until I decided to use `fileValidateTypeDetectType` property while following the example at:

https://pqina.nl/filepond/docs/getting-started/examples/validate-file-type/

```js
// vueFilePond
<file-pond
    accepted-file-types="image/jpeg, image/jpg, image/png, image/webp"
```

```js
// setOptions
fileValidateTypeDetectType: (source, type) => {
    new Promise((resolve, reject) => {
        if (/\.jpg|\.jpeg|\.png|\.webp$/.test(source.name)) {
            const extension = source.name.match(/\.jpg|\.jpeg|\.png|\.webp$/)[0].replace(".", "")
            return resolve(`image/${extension}`)
        }
        resolve(type);
    })
}
```

When `fileValidateTypeDetectType` is used, filepond fails on every file type even the ones listed on `accepted-file-types`. Is this supposed to happen?

**Comment by rizkimcitra** [comment]
Hi, are you still having that problem? if yes how you overcome it, I'm facing the same problem.

**Comment by rizkimcitra** [comment]
my solution is, works as expected

```ts
const handleValidateFileType = useCallback((file: File, type: string) => {
    const excludeType = /\.exe|\.vbs|\.pif|\.iso|\.msi|\.bat|\.cmd|\.vb|\.ws|\.pkg|\.wsf|\.scf|\.lnk$/
    return new Promise<string>((resolve, reject) => {
      if (excludeType.test(file.name)) {
        return reject('declined')
      }
      return resolve(type)
    })
  }, [])

``

**Comment by lnfel** [comment]
> Can you create a test case on code sandbox?

Sorry I've been out for a while, I will put some time on this within the week.

**Comment by ndlinh-celtic** [comment]
@lnfel the function fileValidateTypeDetectType must return a Promise. This should work:

```javascript
// setOptions
fileValidateTypeDetectType: (source, type) => {
    return new Promise((resolve, reject) => {
        if (/\.jpg|\.jpeg|\.png|\.webp$/.test(source.name)) {
            const extension = source.name.match(/\.jpg|\.jpeg|\.png|\.webp$/)[0].replace(".", "")
            return resolve(`image/${extension}`)
        }
        resolve(type);
    })
}
```

**Comment by lnfel** [comment]
@ndlinh-celtic can't believed I overlooked doing a `return`, it's already been 4 months lmao. Tried it and that definitely solved it!
