### ISSUE TITLE
MimeType `.csv` resolve behavior

### ISSUE THREAD

**Issue by cavasinf** [pqina/filepond-plugin-file-validate-type#55]
When using `fileValidateTypeDetectType` option, and a `.csv` file. 
Resolved `type` is equal to `application/vnd.ms-excel`.

```js

console.log('fileValidateTypeLabelExpectedTypesMap', fileValidateTypeLabelExpectedTypesMap)
console.log('acceptedFileTypes', acceptedFileTypes)

FilePond.create(input, {
    acceptedFileTypes: acceptedFileTypes,
    fileValidateTypeLabelExpectedTypesMap: fileValidateTypeLabelExpectedTypesMap,
    fileValidateTypeDetectType: (source, type) => new Promise((resolve, reject) => {
        if (acceptedFileTypes.includes('*')) resolve(type)

        console.log('source', source)
        console.log('type', type)
    }),
}
```

#### Console Logs
```js
fileValidateTypeLabelExpectedTypesMap
{
  "video/mp4": ".mp4",
  "video/mp4v-es": ".mp4",
  "video/x-m4v": ".mp4",
  "video/quicktime": ".mov",
  "video/x-flv": ".flv",
  "application/x-flash-video": ".flv",
  "flv-application/octet-stream": ".flv",
  "video/flv": ".flv",
  "video/avi": ".avi",
  "video/divx": ".avi",
  "video/msvideo": ".avi",
  "video/vnd.divx": ".avi",
  "video/x-avi": ".avi",
  "video/x-msvideo": ".avi",
  "application/zip": ".zip",
  "application/x-zip": ".zip",
  "application/x-zip-compressed": ".zip",
  "image/jpeg": ".jpg",
  "image/pjpeg": ".jpg",
  "image/png": ".png",
  "image/tiff": ".tiff",
  "text/plain": ".txt",
  "text/csv": ".csv",
  "application/csv": ".csv",
  "text/x-comma-separated-values": ".csv",
  "text/x-csv": ".csv",
  "image/vnd.dwg": ".dwg",
  "allowed/extension": ".extra"
}
```

```js
acceptedFileTypes
[
  "text/csv",
  "application/csv",
  "text/x-comma-separated-values",
  "text/x-csv"
]
```

```js
source
File {
   _relativePath: "", 
   name: "Liste des enregistrements étrange.csv", 
   lastModified: 1593700466300, 
   webkitRelativePath: "", 
   size: 8263, 
   type: "application/vnd.ms-excel" 
}
```

```js
type application/vnd.ms-excel
```

But that mime type doesn't match with `csv` file.
Even looking through [Mozilla Doc](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types).

On the other hand,
Resolving with other libs like [Symfony Mime](https://github.com/symfony/mime) (for PHP side) that used [jshttp mime-db](https://github.com/jshttp/mime-db) => https://github.com/symfony/mime/blob/6.2/Resources/bin/update_mime_types.php

Which data comes from that query : https://cdn.jsdelivr.net/gh/jshttp/mime-db@v1.49.0/db.json
I've got this result:
```js
[ "text/csv", "application/csv", "text/x-comma-separated-values", "text/x-csv" ]
```

At the end, passing that array to `acceptedFileTypes` and uploading a `.csv` file, FilePond denied the file.

I've found in the plugin, that MimeType are pulled from:
https://github.com/pqina/filepond-plugin-file-validate-type/blob/c127d54fbd10a78955fc4cae8717c6918e393dc9/src/js/index.js#L94

1. Is there a way to know where that comes from/How that list is implemented?
3. Can we modify that?

#### Versions
```bash
root@1c5566776a87:/var/www/html# yarn list --pattern filepond
yarn list v1.22.19
- filepond-plugin-file-validate-size@2.2.8
- filepond-plugin-file-validate-type@1.2.8
- filepond@4.30.4
```

**Comment by rikschennink** [comment]
You should set a list of mime types that you accept. 

In the `fileValidateTypeDetectType` function you detect the type, in this case probably based on the `.csv` extension, and return one of the CSV mime types that you accept (not the type the browser detects).

**Comment by cavasinf** [comment]
>  in this case probably based on the .csv extension

That was the problem.
Uploading a .csv NAMED file which is not a real CSV file 
was catched as a `text/plain`.

Added more check in my code to not allow "false" file type.
Thanks 👍
