### ISSUE TITLE
File types are empty

### ISSUE THREAD

**Issue by chiex** [pqina/filepond-plugin-file-validate-type#6]
Hi, 

I am wondering why some files have an empty file type when you check on the source.  An example is my test.log file.  I added the file in the pond but when I looked at the source code, here is what I get:
![type](https://user-images.githubusercontent.com/44019553/46723095-98ce5b00-cca9-11e8-9e32-973c8db53eb4.JPG)

the file type is empty/blank. Do you have any idea how or why  it's blank?

Thank you

**Comment by rikschennink** [comment]
Judging from the `File` docs on Mozilla it's because:

> Based on the current implementation, browsers won't actually read the bytestream of a file to determine its media type. It is assumed based on the file extension; a PNG image file renamed to .txt would give "text/plain" and not "image/png". Moreover, file.type is generally reliable only for common file types like images, HTML documents, audio and video. **Uncommon file extensions would return an empty string**.

https://developer.mozilla.org/en-US/docs/Web/API/File/type

**Comment by chiex** [comment]
Thank you for your prompt reply. Is there other way I could get the file type?

**Comment by rikschennink** [comment]
There is now.

Just published version `1.2.0` of the file type validation plugin.
https://pqina.nl/filepond/docs/patterns/plugins/file-validate-type/

You can now set a custom type detector method:

```js
FilePond.create(document.querySelector('input'), {
    acceptedFileTypes: ['image/png'],
    fileValidateTypeDetectType: (source, type) => new Promise((resolve, reject) => {
        console.log(source, type);
        // do custom type detection here and return with promise
        resolve(type);
    })
});
```

**Comment by chiex** [comment]
My Apologies for double posting.

**Comment by bionicmaster** [comment]
Sorry for my comment, the only thing that you need to modify or add is as they said, an async call, this can be made with a promise or putting the keyword async before your function (that's the thing that I'm doing because I have the same issue, but with word files)
