### ISSUE TITLE
Filepond Polyfill and IE 11

### ISSUE THREAD

**Issue by chiex** [pqina/filepond-plugin-file-validate-type#7]
Hi,
I've read that be able to support IE 11, I need to install FilePond Polyfill. How will I add it on my code?

Thanks!

**Comment by rikschennink** [comment]
Add these script tags:
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.6.15/browser-polyfill.min.js"></script>
<script src="https://unpkg.com/filepond-polyfill/dist/filepond-polyfill.js"></script>
```

**Comment by chiex** [comment]
(reposted. seemed my previous post is not saved.)

still not working with IE 11
![image](https://user-images.githubusercontent.com/44019553/47275600-4fec9f80-d5e3-11e8-86cf-428ad7b9911a.png)

error on console:
![image](https://user-images.githubusercontent.com/44019553/47275637-95a96800-d5e3-11e8-8466-3972f1d71b97.png)

and here are the scripts/css in my page:
<apex:stylesheet value="https://unpkg.com/filepond/dist/filepond.css"/>
<apex:includeScript value="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"/> 
<apex:includeScript value="https://unpkg.com/filepond/dist/filepond.min.js"/>
<apex:includeScript value="https://unpkg.com/filepond-plugin-file-encode/dist/filepond-plugin-file-encode.js"/>
<apex:includeScript value="https://unpkg.com/filepond-plugin-file-validate-size/dist/filepond-plugin-file-validate-size.js"/>
<apex:includeScript value="https://unpkg.com/filepond-plugin-file-validate-type/dist/filepond-plugin-file-validate-type.js"/>
<apex:includeScript value="https://unpkg.com/jquery-filepond/filepond.jquery.js"/>
<apex:includeScript value="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.6.15/browser-polyfill.min.js"/>
<apex:includeScript value="https://unpkg.com/filepond-polyfill/dist/filepond-polyfill.js"/>
<apex:includeScript value="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.min.js"/>
<apex:includeScript value="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.auto.min.js"/>

**Comment by chiex** [comment]
test

**Comment by rikschennink** [comment]
You need to move the polyfills to before the other script includes.

```html
<!-- load styles -->
<apex:stylesheet value="https://unpkg.com/filepond/dist/filepond.css"/>

<!-- polyfills, you don't need the es6-promise one -->
<apex:includeScript value="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.6.15/browser-polyfill.min.js"/>
<apex:includeScript value="https://unpkg.com/filepond-polyfill/dist/filepond-polyfill.js"/>
<apex:includeScript value="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"/>

<!-- load filepond -->
<apex:includeScript value="https://unpkg.com/filepond/dist/filepond.min.js"/>
<apex:includeScript value="https://unpkg.com/filepond-plugin-file-encode/dist/filepond-plugin-file-encode.js"/>
<apex:includeScript value="https://unpkg.com/filepond-plugin-file-validate-size/dist/filepond-plugin-file-validate-size.js"/>
<apex:includeScript value="https://unpkg.com/filepond-plugin-file-validate-type/dist/filepond-plugin-file-validate-type.js"/>
<apex:includeScript value="https://unpkg.com/jquery-filepond/filepond.jquery.js"/>
```

**Comment by chiex** [comment]
hi!  it does not work. It's still displaying:
![image](https://user-images.githubusercontent.com/44019553/47337398-4be57e00-d6c6-11e8-9487-5797769c4fd3.png)

No error found on the console.

thank you.

**Comment by rikschennink** [comment]
Please post a screenshot of the browser version info panel.

Plus a code snippet of a minimal test case to reproduce this issue.

**Comment by chiex** [comment]
![image](https://user-images.githubusercontent.com/44019553/47340463-e64abf00-d6d0-11e8-914f-4c677d4f3d3e.png)


<input type="file" 
class="filepond"
name="filepond" 
id="fpond" 												    
multiple ="multiple"
data-max-file-size="10MB"
data-max-files="10"/> 

$( document).ready(function() {
FilePond.registerPlugin(			
			   	FilePondPluginFileEncode,					
				FilePondPluginFileValidateSize,
				FilePondPluginFileValidateType						
			);
			
			// Select the file input and use create() to turn it into a pond			
			FilePond.create(document.querySelector("input[name='filepond']"), {		
			 acceptedFileTypes: ['text/*', 'application/*', 'video/*', 'audio/*,image/*'],	   
			    fileValidateTypeDetectType: (source, type) => new Promise((resolve, reject) => {
			        //console.log(source, type);
			        let fName = source.name;
			        if ('log' === fName.substr((fName.lastIndexOf('.') +1)) ) {
			          source.type = 'text/plain';
			          type = 'text/plain';
			        }    
			        resolve(type);
			    })
			});						
			
			
			FilePond.setOptions({
				labelIdle:  sformat,
				labelTapToCancel: '',
				labelFileLoading: 'Loading...',
				fileValidateTypeLabelExpectedTypes: ''
			}); 
		 
		   FilePond.parse(document.body);

});

**Comment by chiex** [comment]
<input type="file" 
class="filepond"
name="filepond" 
id="fpond" 												    
multiple ="multiple"
data-max-file-size="10MB"
data-max-files="10"/>

**Comment by rikschennink** [comment]
Is this in the page body or are you transpiling this code? 

Why are you loading the jquery adapter when you’re using the native FilePond API?

**Comment by chiex** [comment]
this one - https://unpkg.com/jquery-filepond/filepond.jquery.js? 

oh i forget to take it out. I just removed. still the same.

**Comment by rikschennink** [comment]
That’s your problem, IE11 doesn’t support arrow functions.

**Comment by chiex** [comment]
Got it, i removed the arrow functions and it worked. now I'm back to my previous issue, supporting files with .log extension

**Comment by chiex** [comment]
Thanks, I was able to support  .log extensions
