### ISSUE TITLE
RAR type validation

### ISSUE THREAD

**Issue by followflydge** [pqina/filepond-plugin-file-validate-type#8]
How i can validate RAR types?  
Everyone works with **.zip** file types ``` ['application/zip', 'application/x-compressed', 'application/x-zip-compressed', 'multipart/x-zip']```, but i also need **.rar** types too, like ``` 'application/x-rar-compressed'```

"react-filepond": "^3.0.0",
"filepond-plugin-file-validate-type": "^1.2.0",

**Comment by rikschennink** [comment]
Select a RAR file in the pen below and see what mime type the browser reports it is, then add those mime types to the list.
https://codepen.io/rikschennink/pen/NzRvbj

You can also set up a `fileValidateTypeDetectType` function to do custom type detection.

**Comment by followflydge** [comment]
https://codepen.io/rikschennink/pen/NzRvbj didn't show me anything. 
But i think i can get the file type using *magic numbers* https://en.wikipedia.org/wiki/List_of_file_signatures 
tell me good way, how i can get filesource in fileValidateTypeDetectType?
and mb with small example of fileValidateTypeDetectType realisation

**Comment by rikschennink** [comment]
Then the browser you tested in probably doesn't have a mime type mapping for the file extension.

You can set it up like this:
```js
FilePond.create(document.querySelector('input'), {
    acceptedFileTypes: ['image/png'],
    fileValidateTypeDetectType: (source, type) => new Promise((resolve, reject) => {
        console.log(source, type);
        // do custom type detection here and return with promise
        resolve(type);
    })
});
```

**Comment by followflydge** [comment]
![image](https://user-images.githubusercontent.com/36823884/47850858-c493bb00-dde7-11e8-813d-990c1f01728f.png)
if i add **.zip** fileType everywhere works good
in browser too
but if i add **.rar**  - type is empty ( with different *.rar* files )
![image](https://user-images.githubusercontent.com/36823884/47850935-150b1880-dde8-11e8-9552-b447d4b942e3.png)

**Comment by rikschennink** [comment]
The browser doesn't know what to do with it so can't assign mime type.

You get the file source in the `fileValidateDetectType` method you can thus decide whether you're going to read the actual file data (FileReader) and determine the file type, or for instance, you could use the file extension to return the mime type.

**Comment by followflydge** [comment]
now have 2 arguments with properties, as in the screenshot above. But i think for custom realization of type validation i need fileSource, like third argument in processFunction ( this argument has fileSource in base64 )
How i can take it?

**Comment by rikschennink** [comment]
`file` in your seconds screenshot is the file object itself, the source. You can then use FileReader to turn it into whatever you like.

**Comment by followflydge** [comment]
@rikschennink ty for help!
GJ
