### ISSUE TITLE
aside from JSON, is there other way of retrieving files

### ISSUE THREAD

**Issue by chiex** [pqina/filepond-plugin-file-validate-type#9]
This is more of a question rather than an issue. 

I am using JSON to retrieve files. I put them in a javascript object. before passing to an apex method, I first stringify it. 
In the Apex method, I used deserialize which is my problem because it's giving me an error of **System.LimitException: JSON string exceeds heap size limit**  whenever I upload files that are more 2 or 5mb.

thank you.

**Comment by rikschennink** [comment]
I don't know what you mean by "retrieve files".

**Comment by chiex** [comment]
for (let i = 0; i < $('.filepond--list li').length; i++) {
	var file = JSON.parse($('.filepond--list input').eq(i).val());
		    			 objData.push({'fileName': file.name,
		                          'fileType': file.type,
		                          'fileSize': file.size,
		                          'fileContent': file.data
		                   }); 

...

}

I use the above code to get the files listed on the filepond drag and drop area.  then I use JSOn. stringify and pass it  pass it to a controller. in the controller, I use Json.deserialize but it gave me heap size error mentioned above.

**Comment by rikschennink** [comment]
You call `getFiles` instead:
https://pqina.nl/filepond/docs/patterns/api/filepond-instance/#getting-files

Each returned file item has a `file` property which is the actual file object.

**Comment by chiex** [comment]
Is there an issue with Filepond Encode plugin with large files like 13MB and above? What do you usually use when uploading such kind of files?

**Comment by rikschennink** [comment]
You can upload files async using XMLHttpRequest as multipart form data.

Encoding large files will result in memory trouble on mobile devices and some desktop browsers as well.

**Comment by chiex** [comment]
Thanks!
From your previous post, you mentioned about file property returned by getFiles. How do you get the file body or the actual file content? Filepond File has no property for file body.

Thanks in advance!

**Comment by chiex** [comment]
because when I used this code snippet:

const reader = new FileReader();
reader.onloadend = () => {
      const base64String = reader.result.replace('data:', '').replace(/^.+,/, '');
      // upload file here
};
reader.readAsDataURL(file);

the last syntax gave me a parameter is not of type Blob

Thanks!

**Comment by rikschennink** [comment]
I think this might be of help, you can add the `fileItem.file` object to a `FormData` object.
https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects
